Feat: Login
PedroChaparro/loomies-mobile pull request #41
Opened 2023-02-18 18:54 UTC by PedroChaparro

**Note:** Please, accept #40 first.

Includes: 

1. Reusable button component. 
2. Login form UI. 
3. Login form validation . 
4. Auth context and useAuth hook to share the user session with any component. 
5. Save / recover the tokens from the async storage. 
6. Refresh the access token when the API respond with a 401 status code. 
7. Toasts alerts dependency and hook to make it reusable without repeating code.

2023-02-18 21:19 UTC, Woynert requested changes
Things I have experienced on my end. Running on an physical Android 10 device:
- The text color for the login fields are white. It has low contrast with the background which is gray-ish.
![image](https://user-images.githubusercontent.com/61242172/219899898-4f782433-2c46-4ad0-ab42-915be51d06c4.png)

- There must not be password syntax check in the login screen, it is either a wrong password or a right password, no hints. 

- When you submit wrong credentials, currently the toast says "You are not logged in". I think it'd be better to instead show something like "Wrong email or password".

2023-02-18 21:26 UTC, PedroChaparro commented
>     * There must not be password syntax check in the login screen, it is either a wrong password or a right password, no hints.

Without hints a new user will never know why their password is not valid.

2023-02-18 21:27 UTC, PedroChaparro commented
> Things I have experienced on my end. Running on an physical Android 10 device...

Working on it.

2023-02-18 21:33 UTC, Woynert commented
@PedroChaparro If the user forgot their password they must replace it. Those hints only help account stealers.

2023-02-18 21:34 UTC, PedroChaparro commented
> @PedroChaparro If the user forgot their password they must replace it. Those hints only help account stealers.

Agree, I forgot this isn't the signup screen.

2023-02-18 21:48 UTC, PedroChaparro commented
> Things I have experienced on my end. Running on an physical Android 10 device...

@Woynert, done

2023-02-19 14:55 UTC, SilviaPabon approved these changes
Great 🥳!

2023-02-19 18:18 UTC, Woynert requested changes
Tested on physical Android 10:
- The placeholder still has visibility issues
![image](https://user-images.githubusercontent.com/61242172/219966767-f5a4ef21-26dd-4318-974f-f3480797fade.png)

- Another issue I found is the login endpoint shouldn't treat mail as case sensitive, [I opened and issue for that](https://github.com/PedroChaparro/loomies-backend/issues/52).
- It seems that the first character you type in the mail fiel is upper case by default so the case sensitive issue is even more noticeable.

2023-02-19 19:00 UTC, PedroChaparro commented
> The placeholder still has visibility issues

I think it's done this time. 

> Another issue I found is the login endpoint shouldn't treat mail as case sensitive, [I opened and issue for that](https://github.com/PedroChaparro/loomies-backend/issues/52).

I opened [a Pull Request](https://github.com/PedroChaparro/loomies-backend/pull/53) to close the issue.

2023-02-19 19:18 UTC, Woynert requested changes
About the `yarn start:cache` command please add it as foot note in the readme.

2023-02-19 19:18 UTC, Woynert commented on .env.example
> +API_URL = API IP or DNS url
I suggest adding an example like `http://127.0.0.1:8080` so that you don't have to guess how it will be interpreted.

2023-02-20 19:52 UTC, Woynert approved these changes

2023-02-20 19:52 UTC, merged