Feat: View map 3D
PedroChaparro/loomies-mobile pull request #44
Opened 2023-02-28 17:02 UTC by Woynert

## View
- 3D Map View using Babylon.js.
- 3D Map debug helpers.

	![image](https://user-images.githubusercontent.com/61242172/221918799-2993f239-1af2-433d-854d-0496cf1eaaee.png)

- 3D Models added (`/assets/models`):
	- Player
	- Circle Indicator
	
## Functionality
- Map data is fetched from OpenStreetMaps into custom data structure.
- Added various mesh build methods to generate the map tiles:
	- Vertex array to flat 3D path builder.
	- Gradient plane builder.
	- Road with margin builder.

- Added Map provider to store map data.
- Added Geolocation provider.
- Added device sensors provider.
- Automatically detect player is out of boundaries to trigger new map generation.
- Added Player map indicator in sync with device rotation.
- Added lerp animations for player translations and rotations.

## Developer config added
- Support importing files from `/src` (i.e. `import module from @src/context/module.ts`).
- 3D model indexing and importer.
- MAP_DEBUG environment variable added which enables some debug functionality.

## Notes
- Babylon.js may not work using an emulator. All development was tested on an physical Android 10.
- Enable the MAP_DEBUG mode for better testing. See `.env.example`. (Remember to clean the cache with `yarn start:cache`)
- When MAP_DEBUG is enabled the position update is manually controlled with the onscreen buttons. The GPS will be used only once at the beginning.
- Style and colors are subject to change.

2023-03-07 01:57 UTC, PedroChaparro requested changes

2023-03-07 01:57 UTC, PedroChaparro commented on android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
@Woynert do we need both permissions, based on [some information](https://www.youtube.com/watch?v=8KJH5jwmOPU) i found, just using the ACCESS_FINE_LOCATION should be OK.

2023-03-07 01:57 UTC, PedroChaparro commented on metro.config.js
> +    assetExts: [
@Woynert Is it possible to only define the extensions we'll need? For example, I don't think we'll need the html or pdf extensions.

2023-03-07 01:57 UTC, PedroChaparro commented on src/context/MapProvider.tsx
> +export const MapProvider = (props: { children: any }) => {
You can use the ReactNode type instead of any.

2023-03-07 01:57 UTC, PedroChaparro commented on src/context/SensorProvider.tsx
> +export const SensorProvider = (props: { children: any }) => {
(Duplicated) You can use the ReactNode type instead of any.

2023-03-07 01:57 UTC, PedroChaparro commented on src/context/UserPositionProvider.tsx
> +export const UserPositionProvider = (props: { children: any }) => {
(Duplicated) You can use the ReactNode type instead of any.

2023-03-07 01:57 UTC, PedroChaparro commented on src/components/Map3D/utilsVertex.ts
> +/*
I think this file could have some comments to make it easier for the rest of us to read the code.

2023-03-07 17:02 UTC, Woynert commented
@PedroChaparro Requested changes made.

2023-03-07 17:39 UTC, PedroChaparro approved these changes
Amazing, good work

2023-03-11 14:23 UTC, SilviaPabon approved these changes

2023-03-11 14:24 UTC, merged