Feat: Show wild Loomies in 3D map
PedroChaparro/loomies-mobile pull request #51
Opened 2023-03-24 21:44 UTC by Woynert

# What's new

- Fetches Loomies near the player periodically.
- Loomies get stored and only those who change (aka got deleted or just spawned) are updated.
- Loomies are repositioned when the player is out of bounds.
- Fixes the methods for fetching gyms and Loomies, so it tries to refresh the Access-Token before giving up.
- Optimized the way the models are created. This optimization caused some models to have some body parts rotated in the wrong direction but nothing hard to fix.
- Fixes some models issues like de Spiky Crab (005) having a twisted leg. There could be other models with these problems but we'll fix them as they are reported.

![image](https://user-images.githubusercontent.com/61242172/227645702-a8305265-173b-43da-ad14-7f2bc4efae2c.png)

# How to try

Hop onto the app and you should be able to see some Loomies lurking around. You can preview the models using this tool (https://sandbox.babylonjs.com/).

2023-03-25 00:22 UTC, PedroChaparro approved these changes
Good work. I got around 20-25 FPS using the DEBUG mode.

2023-03-25 00:33 UTC, PedroChaparro requested changes
You should update the branch to use the up to date endpoints.

2023-03-25 00:33 UTC, PedroChaparro commented on src/services/map.services.ts
> +      `${API_URL}/near_loomies`,
This endpoint is `/loomies/near` now.

2023-03-25 01:19 UTC, PedroChaparro approved these changes

2023-03-25 03:41 UTC, SilviaPabon commented
I obtained between 19 and 47 fps, but as general, values between 20 and 30 fps

2023-03-25 03:43 UTC, SilviaPabon commented on src/utils/utils.ts
>  };
Houston 🎙️ @Woynert Are you sure that '019' is the 0.18.png?

2023-03-27 19:07 UTC, SilviaPabon commented on src/utils/utils.ts
>  };
@Woynert 📢 🚨

2023-03-28 02:47 UTC, SilviaPabon approved these changes

2023-03-28 02:47 UTC, merged