Vista recuperar contraseña
PedroChaparro/loomies-mobile pull request #53
Opened 2023-03-27 18:57 UTC by SilviaPabon

Includes:
- Reset Password Page (this view is to request a code with the email)
![image](https://user-images.githubusercontent.com/62608580/228037937-ade2e35d-6197-4ad4-872c-3e1a07e9de9b.png)
- Change Password View (with the code sended to the email, this page allows insert the code and change the password)
![image](https://user-images.githubusercontent.com/62608580/228039294-71c81a97-dbe9-419e-9c9b-d8523ba23c20.png)
- Reset Password from profile page (link to 2 previous pages) (This add some advances with profile page, but is not finished yet)

2023-03-27 19:10 UTC, PedroChaparro commented on src/pages/Profile.tsx
> +            <Text style={Styles.linkText}>settings 1</Text>
Just let the rest password option for now.

2023-03-28 00:46 UTC, PedroChaparro requested changes

2023-03-28 00:46 UTC, PedroChaparro commented on src/pages/Profile.tsx
> +        <Text style={Styles.headerTitle}>PROFILE</Text>
Can you also center this vertically?

2023-03-28 00:46 UTC, PedroChaparro commented on src/pages/Profile.tsx
> +        <TouchableOpacity
Did you used `TouchableOpacity` for some reason? I suggest to use `TouchableWithoutFeedback` instead.

2023-03-28 00:46 UTC, PedroChaparro commented on src/pages/ChangePasswordView.tsx
> +interface ChangePasswordViewProps {
Both props can be optional to avoid Linter error, check the changes in #52.

2023-03-28 00:46 UTC, PedroChaparro commented on src/pages/Profile.tsx
> +        <Text style={Styles.mainTitle}>{user?.email}</Text>
I think it's not necessary to display the user's email. The username it's OK, but if someone sees the email can use it to request a password reset.

2023-03-28 00:46 UTC, PedroChaparro commented on src/pages/Profile.tsx
> +            <FeatherIcon name={'lock'} size={20} color={'black'} />
1. The icons and the texts are using different text colors. I think it's better to use the same for all, try with "#5c5c5c".

2. Can you separate this as a reusable component? Maybe the component can receive the icon name, the text to display and the name of the view to redirect.

2023-03-28 05:49 UTC, SilviaPabon commented
> 1. The icons and the texts are using different text colors. I think it's better to use the same for all, try with "#5c5c5c".
> 2. Can you separate this as a reusable component? Maybe the component can receive the icon name, the text to display and the name of the view to redirect.

@PedroChaparro Tell what do you think 🤔 about the new changes!

2023-03-30 20:37 UTC, Woynert requested changes
There is a security vulnerability with the current password reset implementation. See https://github.com/PedroChaparro/loomies-backend/issues/78.

Aside from that I've found some usability issues:
- There is no clear indication where you must put the code or where to put the password.
- There is not a second field to confirm the password.
- I suggest using placeholders or labels like "Security code here" "Password here" "Confirm password".

![image](https://user-images.githubusercontent.com/61242172/228958056-96c86ef1-b361-4106-9750-635f9e6e52ea.png)

2023-03-30 21:48 UTC, PedroChaparro commented
>
>     * There is not a second field to confirm the password.
> 

@Woynert, The `/session/signup` endpoint and the Signup page on the client neither have that field, should we add it?

2023-03-30 21:55 UTC, Woynert commented
> @Woynert, The `/session/signup` endpoint and the Signup page on the client neither have that field, should we add it?

@PedroChaparro That should be checked only on the client side. Yes, ideally it should be added to the Sign Up form.

2023-04-03 06:21 UTC, SilviaPabon commented
> There is a security vulnerability with the current password reset implementation. See [PedroChaparro/loomies-backend#78](https://github.com/PedroChaparro/loomies-backend/issues/78).
> 
> Aside from that I've found some usability issues:
> 
> * There is no clear indication where you must put the code or where to put the password.
> * There is not a second field to confirm the password.
> * I suggest using placeholders or labels like "Security code here" "Password here" "Confirm password".
> 
> ![image](https://user-images.githubusercontent.com/61242172/228958056-96c86ef1-b361-4106-9750-635f9e6e52ea.png)

@Woynert and @PedroChaparro I made the requested changes

2023-04-03 22:10 UTC, Woynert approved these changes
Good work!
I noticed there is not an issue for logout so I created it #58.

2023-04-04 01:43 UTC, PedroChaparro approved these changes
Gw

2023-04-04 01:43 UTC, merged