Dialogue Fuse Loomies
PedroChaparro/loomies-mobile pull request #64
Opened 2023-04-07 21:47 UTC by andres123dbh

- Show the floating button if the loomie is not busy
- Shows the loomis of the same serial and different from him
- If you don't have loomies it shows a message
- When you successfully merge loomies it goes to the loomies inventory

2023-04-07 22:48 UTC, PedroChaparro requested changes

2023-04-07 22:48 UTC, PedroChaparro commented on src/services/user.services.ts
> +export const fuseLoomies = async (
You are not retrying the request when the response is a 401 (Access Token expired).

2023-04-21 03:17 UTC, Woynert approved these changes

2023-04-21 20:36 UTC, PedroChaparro approved these changes
LGTM

2023-04-21 20:36 UTC, merged