Modal Change Loomball during capture
PedroChaparro/loomies-mobile pull request #84
Opened 2023-04-28 22:09 UTC by andres123dbh

- Show the user's loomballs in modal
- Color the border of the pressed loomball
- Update capture view and selected loomBall

2023-04-28 23:16 UTC, PedroChaparro commented
Depends on [#97](https://github.com/PedroChaparro/loomies-backend/pull/97) now due to a field change

2023-04-28 23:31 UTC, PedroChaparro commented on src/components/Modals/SelectLoomBall.tsx
> +  const getUserLoomBalls = async () => {
This is sending a request to the backend **every time the user changes the Loomball**. We don´t need that and and that can turn into a huge performance issue. 

I'll fix this, but be careful with the API calls and the `useEffect` hook.

2023-04-28 23:34 UTC, PedroChaparro requested changes

2023-04-28 23:34 UTC, PedroChaparro commented on src/components/Modals/SelectLoomBall.tsx
> +  const [loomBall, setLoomBall] = useState<TLoomball[]>([]);
This names are confusing. Please, change 'em to loomballs, setLoomballs and selectedLoomball, setSelectedLoomball.

2023-04-29 00:03 UTC, PedroChaparro approved these changes

2023-04-29 23:34 UTC, Woynert approved these changes
Good job!

2023-04-29 23:35 UTC, merged